spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
springdoc:
  enable-native-support: true
  swagger-ui:
    use-root-path: true
management:
  endpoints:
    web:
      exposure:
        include: refresh